const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2347087627937";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "true", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'

"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail","SUHAIL_15_45_06_18_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTI2LFxuICAgICAgICA0LFxuICAgICAgICAxMzUsXG4gICAgICAgIDM3LFxuICAgICAgICA5NSxcbiAgICAgICAgMTY3LFxuICAgICAgICAxOTgsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjM5LFxuICAgICAgICAxMCxcbiAgICAgICAgMjIxLFxuICAgICAgICAzOSxcbiAgICAgICAgNDksXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTY2LFxuICAgICAgICAxMDIsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMjMyLFxuICAgICAgICA0MSxcbiAgICAgICAgOTIsXG4gICAgICAgIDEwLFxuICAgICAgICAxNDIsXG4gICAgICAgIDE3OCxcbiAgICAgICAgNTYsXG4gICAgICAgIDYzLFxuICAgICAgICAyNSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxNTcsXG4gICAgICAgIDYyLFxuICAgICAgICA5NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzNixcbiAgICAgICAgMjA4LFxuICAgICAgICAxNDksXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTMwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMCxcbiAgICAgICAgMyxcbiAgICAgICAgODQsXG4gICAgICAgIDQyLFxuICAgICAgICAxNzksXG4gICAgICAgIDk2LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjM0LFxuICAgICAgICAyMTQsXG4gICAgICAgIDksXG4gICAgICAgIDExLFxuICAgICAgICAxNjYsXG4gICAgICAgIDYwLFxuICAgICAgICAyMTcsXG4gICAgICAgIDExMCxcbiAgICAgICAgNzUsXG4gICAgICAgIDEzLFxuICAgICAgICAxNTgsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMjE2LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE1LFxuICAgICAgICA0MyxcbiAgICAgICAgNjRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2OCxcbiAgICAgICAgOTgsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNTIsXG4gICAgICAgIDI0LFxuICAgICAgICA0MSxcbiAgICAgICAgMjE4LFxuICAgICAgICAxMjgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTc1LFxuICAgICAgICAxMDAsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTkwLFxuICAgICAgICAyMDgsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjMyLFxuICAgICAgICA0MCxcbiAgICAgICAgMTE4LFxuICAgICAgICAyMDQsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMjcsXG4gICAgICAgIDIzMixcbiAgICAgICAgNDcsXG4gICAgICAgIDM5LFxuICAgICAgICA5OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTUsXG4gICAgICAgIDcyLFxuICAgICAgICA4MSxcbiAgICAgICAgMSxcbiAgICAgICAgNTgsXG4gICAgICAgIDI0NSxcbiAgICAgICAgOTAsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTI0LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTQyLFxuICAgICAgICAxNzIsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNjAsXG4gICAgICAgIDgyLFxuICAgICAgICA1MCxcbiAgICAgICAgMjEzLFxuICAgICAgICAyLFxuICAgICAgICAxMTksXG4gICAgICAgIDk4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTI5LFxuICAgICAgICA4MSxcbiAgICAgICAgMzgsXG4gICAgICAgIDE3MixcbiAgICAgICAgNjEsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTEwLFxuICAgICAgICAxNjUsXG4gICAgICAgIDgwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1NixcbiAgICAgICAgNzgsXG4gICAgICAgIDE0LFxuICAgICAgICAxNzcsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTAsXG4gICAgICAgIDc4LFxuICAgICAgICAyNTMsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTUxLFxuICAgICAgICAyMzUsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMzMsXG4gICAgICAgIDg3LFxuICAgICAgICAxODQsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTIyLFxuICAgICAgICA3NyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyNDMsXG4gICAgICAgIDExMixcbiAgICAgICAgMTk5LFxuICAgICAgICAzOSxcbiAgICAgICAgNyxcbiAgICAgICAgNTEsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjU0LFxuICAgICAgICA2NSxcbiAgICAgICAgMTMyLFxuICAgICAgICAxNTAsXG4gICAgICAgIDEwNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0MixcbiAgICAgICAgNjQsXG4gICAgICAgIDcsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjUsXG4gICAgICAgIDEzNyxcbiAgICAgICAgODcsXG4gICAgICAgIDc2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDQzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTU0LFxuICAgICAgICAxMDgsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjIzLFxuICAgICAgICAxODUsXG4gICAgICAgIDIyLFxuICAgICAgICA5NyxcbiAgICAgICAgMTg0LFxuICAgICAgICA5MSxcbiAgICAgICAgNDksXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMzcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMzIsXG4gICAgICAgIDIxMCxcbiAgICAgICAgODIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgODksXG4gICAgICAgIDEyNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgNzdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMyxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAzMSxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAxMTdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjIsXG4gICAgICAgIDM1LFxuICAgICAgICAxNDEsXG4gICAgICAgIDIzNixcbiAgICAgICAgODksXG4gICAgICAgIDEzMSxcbiAgICAgICAgNjAsXG4gICAgICAgIDc2LFxuICAgICAgICA5LFxuICAgICAgICAxMjIsXG4gICAgICAgIDk2LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE1NixcbiAgICAgICAgODAsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNDIsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMjQzLFxuICAgICAgICA5NSxcbiAgICAgICAgMjI1LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyOCxcbiAgICAgICAgMTQ4LFxuICAgICAgICA3MSxcbiAgICAgICAgNzIsXG4gICAgICAgIDYyLFxuICAgICAgICA2NyxcbiAgICAgICAgMTEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgODQsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTcxLFxuICAgICAgICAyMTAsXG4gICAgICAgIDk4LFxuICAgICAgICA2OCxcbiAgICAgICAgMjQ2LFxuICAgICAgICA4OCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAzOCxcbiAgICAgICAgMTk5LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxNzksXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA5NSxcbiAgICAgICAgMjA1LFxuICAgICAgICAyMDgsXG4gICAgICAgIDExNCxcbiAgICAgICAgMjU0LFxuICAgICAgICAxNjgsXG4gICAgICAgIDUsXG4gICAgICAgIDQ5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDM0LFxuICAgICAgICAxODIsXG4gICAgICAgIDExMixcbiAgICAgICAgMjA2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTQwXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxOTgsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiYmdpNW9pdTUvcEU2aDdhNUM3Vk5Jd1V3a1BZK3BZU1hmQXdvT1F3NzRjVT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiUG1NeXNpOVZRZVdlR1o5S1hmUk9sUVwiLFxuICBcInBob25lSWRcIjogXCI1MWFiMzljZC1hZGIxLTRiMTQtOTk3Zi03NTM3NDAxZjc4OTBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMzAsXG4gICAgICA2MixcbiAgICAgIDMsXG4gICAgICAxMzQsXG4gICAgICA5NCxcbiAgICAgIDE1LFxuICAgICAgMjQ0LFxuICAgICAgMzUsXG4gICAgICAxMTAsXG4gICAgICA5MyxcbiAgICAgIDc3LFxuICAgICAgMTI1LFxuICAgICAgNjcsXG4gICAgICAyMTMsXG4gICAgICAyMDYsXG4gICAgICAyMjYsXG4gICAgICAyNDEsXG4gICAgICAyNDEsXG4gICAgICAxMDgsXG4gICAgICAxOTFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMCxcbiAgICAgIDEzNCxcbiAgICAgIDE1MSxcbiAgICAgIDQ0LFxuICAgICAgMjQ2LFxuICAgICAgMjI0LFxuICAgICAgNTcsXG4gICAgICA3NixcbiAgICAgIDEyNSxcbiAgICAgIDE2OSxcbiAgICAgIDE2OCxcbiAgICAgIDc5LFxuICAgICAgMjgsXG4gICAgICA3NSxcbiAgICAgIDk0LFxuICAgICAgMTE4LFxuICAgICAgMTM5LFxuICAgICAgMjAsXG4gICAgICAyNCxcbiAgICAgIDE4NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJOSjZHM05KN1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0NzA4NzYyNzkzNzoxNUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIkpvc2hfR3JhcGhpY3NkZXNpZ24uRnJhbWVzIEx0ZFwiLFxuICAgIFwibGlkXCI6IFwiMTc5ODczMjMwMzc3MTc5OjE1QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ1AvTHBzOEZFUFRXeHJNR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiL1ZpY2U0K3phK3hYd1JKelZzRytadEthWFV2cm9yOG1wOFVwbXJINHFqaz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCI0MWNsZm5KdW4rUkF6a0JhUng2RUpzV1JBQlFVQXMzVDdSM0FXN1haZHFJM3cwa3JVTTV3eGQ3WWhBOW40cm9pK1lTVEtmREREMVp2MWpyUVRJWVRDUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJ4MTBsSjNCOS9jbVdiTWxWaVk5dXlnMXM5UjR4QmVBaStrQURuem9SbjVWVkRWakcxNzdCWmNNUFg5bUMzcllDQmxqL1lXT2tzL0ovUHk1Wk90ZmJnZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ3MDg3NjI3OTM3OjE1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICA1N1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE4NzI1NDk2LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBUDZXXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQNlcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJNR1BkZndhNCtFL2Z6eUhyS2IrSlNITmNwcWhGejRsMXZNdXdIdys2RkZJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1MDg0ODQ2MDMsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTg3MTA4MzgzMTBcIn0iCn0="


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "truey",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
